### ISSUE TITLE
Netatmo authentication changed

### ISSUE THREAD

**Issue by vedmia** [joshuabeny1999/netatmo-influx-importer#2]
After may months it has stopped working, I believe due to the change in the authentication policy imposed by Netatmo.
Please can you confirm this, and if relevent inform if you are in a position to modify the code

**Comment by joshuabeny1999** [comment]
Hmm yeah it seems also not working anymore on my side. The API is called from my other project: https://github.com/joshuabeny1999/netatmo-api-go 

I will try and update it and then also update this repo to using the latest version of the package. Hope it is an easy fix

**Comment by vedmia** [comment]
Hi

Yes, a real pain!!

Thanks for your quick response.

From initial investigation the token will need to be renewed every three hours, and I cannot find any examples on the Netatamo site.

If you want a beta tester, I volunteer!!

**Comment by joshuabeny1999** [comment]
I could fix it. See new release. The version the app used for authentication was deprecated in october 2022 and still worked. Nice that they provide a way in their gui to generate an refresh-token. So we can store that in our app and i did not had the hussle to implement this 4-step authentication to get a token. 

You can download the new app from the releases (https://github.com/joshuabeny1999/netatmo-influx-importer/releases/tag/v2.0.0) and then update the configuration according to the sample. Remove the username and password and replace it with `refresh_token:`. You can obtain the token by log in on https://dev.netatmo.com/apps/ . There click on the app you created for the importer and scroll down. You will see there a token generator. Choose as scope `read_station` and then copy the Refresh_Token to your config.yml.
